name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with: 
            node-version: "14.x"
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm test
        - name: Build
          run: npm run build --prod
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: advanced_web_frontend
            path: dist/advanced_web_frontend
        - name: Build Image
          run: |
            docker build -t annnfdu/advanced_web_frontend .
        - name: Login to Registry
          run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Image
          run: |
            docker push annnfdu/advanced_web_frontend
        - name: Deploy to Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_NAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            port: ${{ secrets.HOST_PORT }}
            script: |
              docker pull annnfdu/advanced_web_frontend
              docker stop zja_advanced_web_frontend
              docker rm zja_advanced_web_frontend
              docker run -d --name zja_advanced_web_frontend -p 10085:80 annnfdu/advanced_web_frontend